potnanny/api/environments/controllers.py
import datetime
from potnanny.utils import iso_from_sqlite
from potnanny.database import db

async def get_environments() -> dict:
    """
    Get average Temp/Humidity/VPD readings for all rooms
    """

    stmt = """
        SELECT id,name,type,AVG(value),created FROM
            (SELECT id, name FROM room) AS a
            LEFT JOIN (
                SELECT
                    d.id as device_id,
                    d.room_id,
                    m.type,
                    m.value,
                    MAX(m.created) as created
                FROM
                    measurement AS m,
                    device AS d
                WHERE
                    m.device_id = d.id
                AND
                    m.type IN ('temperature', 'humidity', 'vpd')
                GROUP BY
                    d.room_id,
                    d.id,
                    m.type
            ) AS b
            ON a.id = b.room_id
            GROUP BY
                a.id,
                b.type
    """

    data = {}
    rows = []
    async with db.connection():
        rows = await db.fetchall(stmt)

    # reformat the row data
    for row in rows:
        if row[0] not in data:
            data[row[0]] = {
                'id': row[0],
                'name': row[1],
                'measurements': {} }

        if row[3] is not None:
            data[row[0]]['measurements'].update({ row[2]: row[3] })
            data[row[0]]['created'] = iso_from_sqlite(row[4])

    return [data[r] for r in sorted(data.keys())]


async def get_room_environments(pk:int) -> dict:
    """
    Get Device readings for all devices in a room
    """

    stmt = """
        SELECT * FROM
            (SELECT
                r.id AS room_id,
                r.name AS room_name,
                d.id as device_id,
                d.name as device_name
             FROM
                room as r,
                device as d
             WHERE
                r.id = %d
             AND
                d.room_id = %d) AS a
            LEFT JOIN (
                SELECT
                    m.device_id as m_device_id,
                    m.type,
                    m.value,
                    MAX(m.created)
                FROM
                    measurement AS m
                GROUP BY
                    m.device_id,
                    m.type
            ) AS b
            ON a.device_id = b.m_device_id
            ORDER BY
                a.device_id
    """ % (pk, pk)

    data = {}
    rows = []
    async with db.connection():
        rows = await db.fetchall(stmt)

    # reformat the row data
    for row in rows:
        if 'devices' not in data:
            data = {'id': row[0], 'name': row[1], 'devices': {}}

        if row[2] not in data['devices']:
            data['devices'][row[2]] = {
                'id': row[2],
                'name': row[3],
                'measurements': {} }

        if row[5] is not None:
            data['devices'][row[2]]['measurements'].update({ row[5]: row[6] })
            data['devices'][row[2]]['created'] = iso_from_sqlite(row[7])

    data['devices'] = [data['devices'][k] for k in sorted(data['devices'].keys())]
    return data

potnanny/api/environments/views.py
import logging
from quart import Blueprint, jsonify, render_template, abort
from quart_auth import login_required
from jinja2 import TemplateNotFound
from potnanny.models.keychain import Keychain
from .controllers import get_environments, get_room_environments


logger = logging.getLogger(__name__)
bp = Blueprint('environments', __name__, template_folder='templates')


SUFFIXES = {
    'temperature': '°',
    'humidity': '%',
    'battery': '%',
    'soil_moisture': '%',
}


@bp.route('/', methods=['GET'])
@login_required
async def dashboard():
    data = await get_environments()
    try:
        features = await Keychain.select().where(Keychain.name == 'features')[0]
        logger.debug(features)
    except:
        features = None

    try:
        return await render_template('environments/dash.html',
            data=data,
            suffixes=SUFFIXES,
            features=features.as_dict())
    except TemplateNotFound:
        abort(404)


@bp.route('/environments/<int:pk>', methods=['GET'])
@login_required
async def room_dashboard(pk):
    data = await get_room_environments(pk)
    try:
        return await render_template('environments/room.html',
            data=data, suffixes=SUFFIXES)
    except TemplateNotFound:
        abort(404)


@bp.route('/api/v1.0/environments', methods=['GET'])
@login_required
async def environment():
    data = await get_environments()
    if data:
        return jsonify({'status': 'ok', 'msg': data}), 200
    else:
        return jsonify({'status': 'error', 'msg': 'no data'}), 404


@bp.route('/api/v1.0/environments/<int:pk>', methods=['GET'])
@login_required
async def room_environment(pk):
    data = await get_room_environments(pk)
    if data:
        return jsonify({'status': 'ok', 'msg': data}), 200
    else:
        return jsonify({'status': 'error', 'msg': 'no data'}), 404

potnanny/api/environments/templates/environments/dash.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <script>
        var CSRF_TOKEN = "{{ csrf_token() }}";
        try {
            var mySuffixes = {{ suffixes | tojson }};
        } catch(err) {
            // fine
        }
    </script>
    <script src="{{ url_for('static', filename='js/min/chart.umd.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/common.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/environments.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/rooms.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/modals.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/graphs.min.js') }}"></script>

{% endblock %}

{% block content %}
{%- if data -%}
    <div class="row row-cols-1 row-cols-lg-2">
    {%- for room in data -%}
        <div class="col">
            <div class="card mb-3" id="room-{{ room.id }}">
                <div class="card-header">
                    <span class="float-end text-muted fw-light timestamp" style="font-size: 0.85em;" id="room-{{ room.id }}-created">{{ room.created }}</span>
                    <a href="{{ url_for('environments.room_dashboard', pk=room.id) }}" id="room-{{ room.id }}-name" class="text-decoration-none">{{ room.name }}</a>
                    <span class="dropdown ms-1">
                        <button type="button" data-bs-toggle=dropdown class="btn dropdown-toggle py-0 px-1 m-0">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:" class="dropdown-item text-decoration-none" onclick="roomNameModal({{ room.id }})">Rename</a></li>
                            <li><a href="javascript:" class="dropdown-item text-decoration-none" onclick="roomNotesModal({{ room.id }})">Room Notes</a></li>
                            <li><a href="javascript:" class="dropdown-item text-decoration-none" onclick="deleteRoom({{ room.id }})">Delete</a></li>
                        </ul>
                    </span>
                </div>
                <div class="card-body row">
                {%- for key in ['temperature', 'humidity', 'vpd'] -%}
                    {%- if key in room.measurements.keys() -%}
                    <div class="col text-center mb-1">
                        <div class="fs-3">
                            <a href="javascript:" id="room-{{ room.id }}-{{ key }}" onclick="buildModalChart('{{ url_for('graphs.room',pk=room.id, measurement=key, hours=12) }}')" class="text-decoration-none">
                            {%- if key in ['temperature','vpd'] -%}
                                {{ '%0.1f' | format(room.measurements[key]) }}{%- if key in suffixes.keys() -%}{{ suffixes[key] }}{%- endif -%}
                            {% else %}
                                {{ room.measurements[key] | int }}{%- if key in suffixes.keys() -%}{{ suffixes[key] }}{%- endif -%}
                            {%- endif -%}
                            </a>
                        </div>
                        <div class="text-uppercase" style="font-size: 0.6em;">
                            {{ key }}
                        </div>
                    </div>
                    {%- endif -%}
                {%- endfor -%}
                </div>
            </div>
        </div>
    {%- endfor -%}
    </div>
{%- endif -%}

{% if features %}
    {%- if features.attributes.room_limit > data | length -%}
    <div class="mt-3">
        <a href="javascript:" onclick="roomNameModal()" class="btn btn-outline-primary">+</a>
    </div>
    {%- endif -%}
{% endif %}

    <script>
        if (window.addEventListener) {
            window.addEventListener('load', localizeTimestamps, false);
        }

        const deleteRoom = function(pk) {
            Room.load(pk);
            if (confirm("Are you sure you want to delete this room and data?")) {
                Room.delete(Number(pk));
                setTimeout(function() { window.location.reload(); }, 1500);
            }
        }

        window.setInterval(function() {
            Environment.loadList();
        }, 10000);
        window.setInterval(function() {
            updateEnvironments();
        }, 2000);
    </script>
{% endblock %}

potnanny/api/environments/templates/environments/room.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <script>
        var CSRF_TOKEN = "{{ csrf_token() }}";
        try {
            var mySuffixes = {{ suffixes | tojson }};
        } catch(err) {
            console.log(err);
        }
    </script>
    <script src="{{ url_for('static', filename='js/min/common.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/environments.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/rooms.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/devices.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/controls.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/outlets.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/modals.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/graphs.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/min/chart.umd.min.js') }}"></script>
{% endblock %}

{% block content %}
{%- if data -%}
    <h3 class="mb-3">{{ data.name }}</h3>
    <div class="row row-cols-1 row-cols-lg-2">
    {%- for device in data.devices -%}
        <div class="col">
            <div class="card mb-3" id="device-{{ device.id }}">
                <div class="card-header">
                    <span class="float-end text-muted fw-light timestamp" style="font-size: 0.85em;" id="device-{{ device.id }}-created">{{ device.created }}</span>
                    <span id="device-{{ device.id }}-name" class="text-decoration-none">{{ device.name }}</span>
                    <span class="dropdown ms-1">
                        <button type="button" data-bs-toggle=dropdown class="btn dropdown-toggle py-0 px-1 m-0">
                            <i class="bi bi-three-dots-vertical"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="javascript:" onclick="deviceNameModal({{ device.id }})" class="dropdown-item text-decoration-none">Rename</a></li>
                            <li><a href="javascript:" onclick="deviceFormModal({{ device.id }})" class="dropdown-item text-decoration-none">Edit</a></li>
                            <li><a href="javascript:" onclick="deleteDevice(({{ device.id }})" class="dropdown-item text-decoration-none">Delete</a></li>
                        </ul>
                    </span>
                </div>
                <div class="card-body row">
                    {%- for key in device.measurements.keys() | sort -%}
                    <div class="col text-center mb-1">
                        {%- if key.startswith('outlet') -%}
                        <div class="mb-1 mt-1">
                            <button type="button" class="btn btn-outline-primary py-0 px-2 fs-5">
                                <i id="device-{{ device.id }}-{{ key }}" class="bi bi-toggle-{%- if device.measurements[key] == 0 -%}off{% else %}on{%- endif -%}" onclick="toggleOutlet({{ device.id }}, '{{ key }}')" style="font-size: 1.15em"></i>
                            </button>
                            <button type="button" class="btn btn-outline-primary py-0 px-2 fs-5">
                                <i class="bi bi-dpad" onclick="controlForm({{ device.id }}, '{{ key }}')" style="font-size: 1.15em"></i>
                            </button>
                            <button type="button" class="btn btn-outline-primary py-0 px-2 fs-5">
                                <i class="bi bi-file-bar-graph" onclick="buildModalChart('{{ url_for('graphs.device', pk=device.id, measurement=key, hours=12) }}')" style="font-size: 1.15em"></i>
                            </button>
                        </div>
                        {% else %}
                        <div class="fs-3">
                            <a href="javascript:" id="device-{{ device.id }}-{{ key }}" onclick="buildModalChart('{{ url_for('graphs.device', pk=device.id, measurement=key, hours=12) }}')" class="text-decoration-none">
                            {%- if key in ['temperature','vpd'] -%}
                                {{ '%0.1f' | format(device.measurements[key]) }}{%- if key in suffixes.keys() -%}{{ suffixes[key] }}{%- endif -%}
                            {% else %}
                                {{ device.measurements[key] | int }}{%- if key in suffixes.keys() -%}{{ suffixes[key] }}{%- endif -%}
                            {%- endif -%}
                            </a>
                        </div>
                        {%- endif -%}
                        <div class="text-uppercase" style="font-size: 0.6em;">
                            {{ key }}
                        </div>
                    </div>
                    {%- endfor -%}
                </div>
            </div>
        </div>
    {%- endfor -%}
{% endif %}
    <script>
        const myRoom = {{ data.id }};

        RoomEnvironment.loadList(myRoom);
        if (window.addEventListener) {
            window.addEventListener('load', localizeTimestamps, false);
        }

        const deleteDevice = function(pk) {
            Device.load(pk);
            if (confirm("Are you sure you want to delete this device and data?")) {
                Device.delete(Number(pk));
                setTimeout(function() { window.location.reload(); }, 1500);
            }
        }

        window.setInterval(function() {
            RoomEnvironment.loadList(myRoom);
        }, 10000);
        window.setInterval(function() {
            updateRoomEnvironments();
        }, 5000);
    </script>
{% endblock %}