potnanny/api/features/forms.py
from quart_wtf import QuartForm
from wtforms.fields import TextAreaField
from wtforms import validators


class LicenseForm(QuartForm):
     license = TextAreaField(
        'License Key',
        validators=[
            validators.DataRequired('must provide a license key'),
        ]
    )

potnanny/api/features/controllers.py
import asyncio
import logging
from potnanny.database import db
from potnanny.models.keychain import Keychain, KeychainSchema
from potnanny.models.license import License, LicenseSchema


logger = logging.getLogger(__name__)


async def load_license(data:dict):
    try:
        schema = LicenseSchema()
        clean = schema.load(data)
    except:
        return (1, "schema validation failure")

    async with db.transaction() as trx:
        try:
            license = await License.create(**clean)
            if 'actions' in data:
                if 'keychain_updates' in data['actions']:
                    for item in data['actions']['keychain_updates']:
                        kc = await Keychain.select().where(
                            Keychain.name == item['name']).first()
                        if kc:
                            kc.attributes.update(item['attributes'])
                            await kc.save()

                if 'keychain_creates' in data['actions']:
                    for item in data['actions']['keychain_creates']:
                        kc = await Keychain.create(**item)
                        await kc.save()

                if 'downloads' in data['actions']:
                    for item in data['actions']['downloads']:
                        pass

        except Exception as x:
            logger.warning(x)
            await trx.rollback()
            return (2, 'license insert failure')

    return (0, 'ok')

potnanny/api/features/views.py
import logging
import base64
import json
from quart import (Blueprint, jsonify, render_template, abort, flash, request,
    redirect)
from quart_auth import login_required
from jinja2 import TemplateNotFound
from potnanny.database import db
from potnanny.models.keychain import Keychain, KeychainSchema
from potnanny.models.license import License
from .forms import LicenseForm
from .controllers import load_license


logger = logging.getLogger(__name__)
bp = Blueprint('features', __name__, template_folder='templates')


@bp.route('/features', methods=['GET'])
@login_required
async def show_features():
    results = await License.select()

    try:
        return await render_template('features/index.html', data=results)
    except TemplateNotFound:
        abort(404)


@bp.route('/features/import', methods=['GET', 'POST'])
@login_required
async def import_key():
    form = await LicenseForm.create_form()

    if await form.validate_on_submit():
        await request.get_data()
        raw = (await request.form)["license"]
        data = {}

        try:
            b = base64.b64decode(raw)
            logger.debug(b)

            data = json.loads(b)
            logger.debug(data)
            rval, msg = await load_license(data)
            if rval:
                if not getattr(form.license, 'errors'):
                    form.license.errors = []
                form.license.errors.append(msg)

        except Exception as x:
            logger.warning(x)
            if not getattr(form.license, 'errors'):
                form.license.errors = []
            form.license.errors.append('error decoding key')

        if not getattr(form.license, 'errors'):
            await flash('feature license loaded', 'info')
            return redirect("/")
    try:
        return await render_template('features/form.html', form=form)
    except TemplateNotFound:
        abort(404)

potnanny/api/features/templates/features/form.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" id="myForm">
        {{ form.csrf_token }}
        <div class="mt-2">
            <div class="alert alert-warning">
            Do not load any license keys unless they come directly from Potnanny! Someone could be injecting malicious software into your system!
            </div>
        </div>
        <div class="mt-2">
            {{ form.license.label(class_="form-label") }}
            {% if form.license.errors %}
            {{ form.license(class_="form-control is-invalid") }}
            {% else %}
            {{ form.license(class_="form-control") }}
            {% endif %}
            <div class="invalid-feedback" id="license-feedback">
                {% for error in form.license.errors %}
                {{ error }}
                {% endfor %}
            </div>
        </div>
        <div class="row row-cols-2 mt-3">
            <div class="col">
                <input id="submit" type="submit" class="w-100 btn btn-outline-primary" value="Submit">
            </div>
        </div>
    </form>
{% endblock %}

potnanny/api/features/templates/features/index.html
{% extends 'base.html' %}

{% block content %}
<h3>Features</h3>

{% if data %}
    <div class="row row-cols-1 row-cols-lg-2 mt-3">
    {% for license in data %}
        <div class="col mb-2">
            <div class="card">
                <div class="card-header">
                    <span class="float-end text-muted fw-light" style="font-size: 0.85em;">{{ license.created }}</span>
                    {{ license.name }}
                </div>
                <div class="card-body">{{ license.description }}</div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endif %}

    <div class="mt-4">
        <a href="{{ url_for('features.import_key') }}" class="btn btn-outline-primary">Import Feature Key</a>
    </div>
{% endblock %}