potnanny/api/devices/views.py
import asyncio
import logging
import json
import potnanny.controllers.worker as worker
from quart import (Blueprint, jsonify, render_template, abort, request, flash,
    redirect)
from quart_auth import login_required
from jinja2 import TemplateNotFound
from potnanny.models.device import Device, DeviceSchema
from potnanny.models.room import Room
from potnanny.models.keychain import Keychain
from potnanny.database import db, lock
from potnanny.ble import lock as ble_lock
from potnanny.controllers.outlet import switch_device_outlet


logger = logging.getLogger(__name__)
bp = Blueprint('devices', __name__, template_folder='templates')


@bp.route('/devices', methods=['GET'])
@login_required
async def index():
    devices = await Device.select()
    try:
        features = await Keychain.select().where(Keychain.name == 'features')[0]
        logger.debug(features)
    except:
        features = None

    try:
        return await render_template('devices/index.html',
            data=devices, features=features)
    except TemplateNotFound:
        abort(404)


@bp.route('/api/v1.0/devices', methods=['GET'])
@login_required
async def get_list():
    objects = await Device.select()
    if not objects:
        return jsonify({"status": "error", "msg": "object not found"}), 404

    return jsonify({
        "status": "ok", "msg": [o.as_dict()  for o in objects] }), 200


@bp.route('/api/v1.0/devices', methods=['POST'])
@login_required
async def create():
    try:
        jsondata = await request.get_json()
        schema = DeviceSchema()
        data = schema.load(jsondata)
        async with lock:
            async with db.connection():
                obj = await Device.create(**data)
                await obj.save()
        return jsonify({"status": "ok", "msg": obj.as_dict()}), 201
    except Exception as x:
        return jsonify({"status": "error", "msg": str(x) }), 500


@bp.route('/api/v1.0/devices/<int:pk>', methods=['GET'])
@login_required
async def get(pk):
    obj = await Device.get_by_id(pk)
    if not obj:
        return jsonify(
            {"status": "error", "msg": f"object with id {pk} not found"}), 404

    return jsonify({"status": "ok", "msg": obj.as_dict()}), 200


@bp.route('/api/v1.0/devices/<int:pk>', methods=['PATCH'])
@login_required
async def patch(pk):
    try:
        jsondata = await request.get_json()
        schema = DeviceSchema()
        data = schema.load(jsondata)
        async with lock:
            async with db.connection():
                obj = await Device.get_by_id(pk)
                for k, v in data.items():
                    setattr(obj, k, v)
                await obj.save()

        return jsonify({"status": "ok", "msg": obj.as_dict()}), 200
    except Exception as x:
        logger.warning(str(x))
        return jsonify(
            {"status": "error", "msg": f"object with id {pk} not found"}), 404


@bp.route('/api/v1.0/devices/<int:pk>', methods=['DELETE'])
@login_required
async def delete(pk):
    async with lock:
        async with db.connection():
            try:
                obj = await Device.get_by_id(pk)
                await obj.delete_instance()
                await flash("Device deleted", "info")
            except:
                pass

    return jsonify({
        "status": "ok", "msg": ""}), 200


@bp.route('/api/v1.0/devices/<int:pk>/poll', methods=['POST'])
@login_required
async def device_poll(pk):
    asyncio.create_task(worker.WORKER.poll_device(pk))
    return jsonify({"status": "ok", "msg": "polling queued"}), 200


@bp.route('/api/v1.0/devices/<int:pk>/<int:outlet>/on', methods=['POST'])
@login_required
async def device_on(pk, outlet):
    state = 1
    result = await switch_device_outlet(pk, outlet, state)
    if result != state:
        return jsonify({
            "status": "error",
            "msg": f"error switching device {pk} outlet {outlet}"}), 500

    return jsonify({"status": "ok", "msg": {'state': state}}), 200


@bp.route('/api/v1.0/devices/<int:pk>/<int:outlet>/off', methods=['POST'])
@login_required
async def device_off(pk, outlet):
    state = 0
    result = await switch_device_outlet(pk, outlet, state)
    if result != state:
        return jsonify({
            "status": "error",
            "msg": f"error switching device {pk} outlet {outlet}"}), 500

    return jsonify({"status": "ok", "msg": {'state': state}}), 200


@bp.route('/api/v1.0/devices/<int:pk>/keycode', methods=['GET'])
@login_required
async def get_keycode(pk):
    device = await Device.get_by_id(pk)
    if not device:
        return jsonify({
            "status": "error", "msg": "not found"}), 404

    if (not hasattr(device.plugin, 'is_key_required') or
        device.plugin.is_key_required is not True):
        return jsonify({
            "status": "error",
            "msg": "not a valid request for this device"}), 405

    secret = None
    try:
        async with ble_lock:
            secret = await device.plugin.scan_key()
    except Exception as x:
        logger.debug(x)

    if secret:
        return jsonify({"status": "ok", "msg": secret}), 200
    else:
        return jsonify({
            "status": "error",
            "msg": "key code not detected before timeout"}), 404

potnanny/api/settings/views.py
import logging
from quart import Blueprint, jsonify, render_template, abort
from quart_auth import login_required
from jinja2 import TemplateNotFound
from potnanny.models.keychain import Keychain, KeychainSchema
from potnanny.database import db


logger = logging.getLogger(__name__)
bp = Blueprint('settings', __name__, template_folder='templates')


@bp.route('/settings', methods=['GET'])
@login_required
async def index():
    obj = await Keychain.select().where(Keychain.name == 'settings')[0]

    try:
        return await render_template('settings/index.html', title='Settings',
            data=obj.as_dict())
    except TemplateNotFound:
        abort(404)


@bp.route('/api/v1.0/settings', methods=['GET'])
@login_required
async def get():
    try:
        obj = await Keychain.select().where(Keychain.name == 'settings')[0]
        if not obj:
            return jsonify({
                "status": "error", "msg": f"object id {pk} not found"}), 404

        return jsonify({"status": "ok", "msg": obj.as_dict()}), 200
    except Exception as x:
        return jsonify({"status": "error", "msg": str(x)}), 500


@bp.route('/api/v1.0/settings', methods=['PATCH'])
@login_required
async def patch():
    try:
        jsondata = await request.get_json()
        schema = KeychainSchema()
        data = schema.load(jsondata)
        async with db.connection():
            obj = await Keychain.select().where(Keychain.name == 'settings')[0]
            if not obj:
                return jsonify({
                    "status": "error", "msg": f"object id {pk} not found"}), 404

            for k, v in data.items():
                setattr(obj, k, v)
            await obj.save()

        return jsonify({"status": "ok", "msg": obj.as_dict()}), 200
    except Exception as x:
        return jsonify({"status": "error", "msg": str(x)}), 500

potnanny/api/templates/base.html
<!doctype html>

{% autoescape true %}
<html>
    <head>
        {% block head %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/bootstrap-icons.css') }}" rel="stylesheet">
        <script src="{{ url_for('static', filename='js/min/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/min/mithril.min.js') }}"></script>
        <style>
            nav {
                border-bottom: 1px solid #AAA;
            }
        </style>
        {% endblock %}
    </head>
    <body>
        <!-- navigation -->
        <nav class="navbar navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/"><i class="bi bi-flower1"></i> POTNANNY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('devices.index') }}">devices</a></li>
                        <li class="nav-item"><a class="nav-link" href="{{ url_for('settings.index') }}">settings</a></li>
                        <li class="nav-item-dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown">account</a>
                            <ul class="dropdown-menu">
                                <a class="dropdown-item" href="{{ url_for('auth.pwreset') }}">change password</a>
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">logout</a>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- app workspace -->
        <div class="container mt-4">
        {% block content %}
        {% endblock %}

        <!-- notification style toast area -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
            <div class="mt-3">
                {% for category, message in messages %}
                <div class="mt-1 alert alert-{{ category }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        </div>

        <!-- apps modal window -->
        <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
            <div class="modal-dialog modal-xl" role="document">
                <div class="modal-content" id="myModalContent">
                    <div class="modal-header border-0" id="myModalHeader">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body" id="myModalBody">
                    </div>
                </div>
            </div>
        </div>

        <script>
            <!-- fix nav menu operation -->
            const navLinks = document.querySelectorAll('.nav-item');
            const menuToggle = document.getElementById('navbarNav')
            const bsCollapse = new bootstrap.Collapse(menuToggle, {toggle:false})
            navLinks.forEach(function(l) {
                l.addEventListener('click', () => { bsCollapse.toggle() });
            })
        </script>
    </body>
</html>
{% endautoescape %}